[project]
name = "dr-automate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "pillow>=12.1.0",
    "pypdf>=6.6.0",
    "reportlab>=4.4.9",
]
